apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy82
  labels:
    app: autodeploy82
  namespace: namespace-workflow-1714390114058
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy82
  template:
    metadata:
      labels:
        app: autodeploy82
    spec:
      containers:
        - name: autodeploy82
          image: acrworkflow1714390114058.azurecr.io/image-workflow-1714390114058:latest
          ports:
            - containerPort: 5000